[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Adiciona a EmonLib e Firebase
lib_deps = 
    openenergymonitor/EmonLib@^1.1.0
    mobizt/Firebase ESP Client @ ^4.4.14

; Evita problemas de otimização excessiva que possam prejudicar a leitura analógica crua
build_unflags = -Os
build_flags = -O2
